apiVersion: v1
kind: Pod
metadata:
   name: lifecyc-pod
spec:
   containers:
       - name: lifecyc-container
         image: nginx:alpine
         # command for debugging containers lifecycle
         lifecycle:
             postStart:
                 exec:
                    command: ["/bin/sh", "-c", "echo Welcome dinesh > /usr/share/poststart-msg"]
             preStop:
                 exec:
                    command: ["/usr/sbin/nginx", "-s", "quit"]
