apiVersion: v1 
kind: Secret 
metadata:
  name: mysql-secret
type: Opaque
data:
  password: ZGluZXNoMTk5Nw==
  # it is used for a creating a configuration file  
  # secret.file: |
  #   ZldfuFASX==34jksdjflksj34jksLLjflkj