apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: wordpress
  serviceName: mysql-headless-service
  template: 
    metadata:
      labels:
        app: mysql
        tier: wordpress
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec: 
      storageClassName: mysql-pv
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi