apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wordpress
spec:
  accessModes:
  # multiple pod can use this volume at a time
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi