apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    app:  mysql
    tier: wordpress